version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: mediapp-image
    container_name: mediapp
    volumes:
      - .:/home/mediapp/backend-jesus-mediapp/mediapp
      - ./storage:/home/mediapp/backend-jesus-mediapp/mediapp/storage
    ports:
      - "8000:80"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mediapp-network

  db:
    image: postgres:12
    container_name: mediapp_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: mediapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdasdasd123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mediapp-network

volumes:
  postgres_data:

networks:
  mediapp-network:
    driver: bridge