name: Deploy

on:
  push:
    branches:
      - backend-jesus-mediapp
      
jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Login en Amazon ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/r9v6v5c8

      - name: Subir imagen a Amazon ECR
        run: |
          docker tag mediapp-image:latest public.ecr.aws/r9v6v5c8/myecr-repo-public:latest
          docker push public.ecr.aws/r9v6v5c8/myecr-repo-public:latest

      - name: Actualizar la tarea en ECS
        run: |
          aws ecs update-service --cluster mediapp-cluster --service mediapp-service --force-new-deployment