name: Deploy

on:
  push:
    branches:
      - backend-jesus-mediapp

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ AKIA4IM3HTCRCZYP62EA }} #agregar id de AWS
          aws-secret-access-key: ${{ 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 }} #agregar contraseña AWS
          aws-region: us-east-2  # Cambia por tu región de AWS tambien modificar demás cosas

      - name: Login en Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin AKIA4IM3HTCRCZYP62EA.ecr.us-east-2.amazonaws.com

      - name: Subir imagen a Amazon ECR
        run: |
          docker tag backend_mediapp:latest AKIA4IM3HTCRCZYP62EA.dkr.ecr.us-east-2.amazonaws.com/repo-mediapp-backend:latest
          docker push AKIA4IM3HTCRCZYP62EA.dkr.ecr.us-east-2.amazonaws.com/repo-mediapp-backend:latest

      - name: Actualizar la tarea en ECS
        run: |
          aws ecs update-service --cluster mediapp-cluster --service mediapp-service --force-new-deployment